version: '3'

service:
  do:
    image: mysql
    ports:
      - '32000:3306'
    envirioment:
      MYSQL_DATABASE: 'boticario'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root123@'
      MYSQL_ROOT_PASSWORD: 'root123@'

    web:
      build: *
      image: image-boticario:1.0.0
      command: python -m flask run
      volumes:
        - .:/app
      ports:
        - "8000:8000"
      depends_on:
        - db